apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: first-pipeline-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.4.1, pipelines.kubeflow.org/pipeline_compilation_time: '2021-04-11T17:26:18.795222',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "Applies Decision Tree
      and Logistic Regression for classification problem.", "name": "First Pipeline"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.4.1}
spec:
  entrypoint: download-data-function
  templates:
  - name: download-data-function
    container:
      args: []
      command: [python, download_data.py, --data, /tmp/outputs/Data/data]
      image: fernandolpz/only-tests:download_data_v3
    outputs:
      artifacts:
      - {name: download-data-function-Data, path: /tmp/outputs/Data/data}
    metadata:
      annotations: {pipelines.kubeflow.org/component_spec: '{"description": "Download
          toy data from sklearn datasets", "implementation": {"container": {"command":
          ["python", "download_data.py", "--data", {"outputPath": "Data"}], "image":
          "fernandolpz/only-tests:download_data_v3"}}, "name": "Download Data Function",
          "outputs": [{"description": "Path where data will be stored.", "name": "Data",
          "type": "LocalPath"}]}', pipelines.kubeflow.org/component_ref: '{"digest":
          "8db794668b4fd3b82638d89a42251f4038ab56623ee9f34721c356c5479155d2", "url":
          "download_data/download_data.yaml"}'}
  - name: testing-function
      container:
        args: [ ]
        command: [ python, testing.py, --data, /tmp/outputs/Data/data ]
        image: fernandolpz/only-tests:testing_v3
      outputs:
        artifacts:
          - { name: testing-function-Data, path: /tmp/outputs/Data/data }
  arguments:
    parameters: []
  serviceAccountName: pipeline-runner
