apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: kubeflow-pipeline-
spec:
  entrypoint: my-pipeline
  templates:
    - name: my-pipeline
      steps:
        - - name: step-1
            template: testing
  workflows:
    - name: testing
      template:
        name: testing
        container:
          image: my-container-image:latest
          command: ["python", "testing.py"]
